# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDcdisohCwAHpdRwP3OecGeDVfuzNBlM

#  Dataset Importing and Overview
"""

#Importing necessary libraries for data cleaning and visualization
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

#Importing the data set and showing its number of rows and columns, respectively
df = pd.read_csv('https://raw.githubusercontent.com/Youssef-888/Procurement-Spend-Analysis/refs/heads/main/spend_analysis_dataset.csv')
df.shape

#Showing first 5 rows of the data set
df.head()

#Showing the last 5 rows of the data set
df.tail()

#Displaying important measures for quantitative data set columns
df.describe()

"""# Which Suppliers Account for the Highest Proportion of Total Spending?

"""

# Group the DataFrame by 'Supplier' and sum the 'TotalCost' for each supplier
top_suppliers = df.groupby('Supplier')['TotalCost'].sum().sort_values(ascending=False)

# Create a bar plot to visualize the total cost per supplier, sorted in descending order
top_suppliers.plot(kind='bar', figsize=(10, 5), title='Total Spend by Supplier')

# Label the y-axis as 'Total Cost'
plt.ylabel('Total Cost')

# Display the plot
plt.show()

"""# Are There Seasonal Trends in Spending?"""

# Convert the 'PurchaseDate' column to datetime format
df['PurchaseDate'] = pd.to_datetime(df['PurchaseDate'])

# Extract the month from 'PurchaseDate' and create a new 'Month' column
df['Month'] = df['PurchaseDate'].apply(lambda x: x.month)

# Group the data by 'Month' and sum the 'TotalCost' for each month
monthly_spending = df.groupby('Month')['TotalCost'].sum()

monthly_spending.plot(kind='bar', figsize=(10, 5), title='Monthly Spending')

plt.xlabel('Month')

plt.ylabel('Total Cost')

plt.show()

"""# Is Spending Higher in Q4 Than Q1?"""

# Define a function to assign a quarter based on the month
def get_quarter(month):
    if month in [1, 2, 3]:
        return 1  # Q1
    elif month in [4, 5, 6]:
        return 2  # Q2
    elif month in [7, 8, 9]:
        return 3  # Q3
    else:
        return 4  # Q4

# Apply the function to create a new 'Quarter' column in the DataFrame
df['Quarter'] = df['Month'].apply(get_quarter)

# Filter the 'TotalCost' values for Q1 and Q4
q1 = df[df['Quarter'] == 1]['TotalCost']
q4 = df[df['Quarter'] == 4]['TotalCost']

# Print the average spending for Q1 and Q4
print(f"Average Q1 Spending: ${q1.mean():.2f}")
print(f"Average Q4 Spending: ${q4.mean():.2f}")

# Create a boxplot to compare the distribution of spending between Q1 and Q4
plt.boxplot([q1, q4], labels=['Q1', 'Q4'])
plt.title('Spending Comparison: Q1 vs Q4')
plt.ylabel('Total Cost')
plt.show()

# Import the t-test function from SciPy
from scipy.stats import ttest_ind

# Perform a two-sample t-test assuming unequal variances (Welch's t-test)
t_stat, p_val_two_tailed = ttest_ind(q4, q1, equal_var=False)

# Convert the two-tailed p-value to a one-tailed p-value
# Since we're testing if Q4 spending is greater than Q1
p_val_one_tailed = p_val_two_tailed / 2

# Print the t-statistic and one-tailed p-value
print(f"T-statistic: {t_stat:.2f}")
print(f"One-tailed P-value: {p_val_one_tailed:.4f}")

alpha = 0.05

# Interpret the result of the hypothesis test
if p_val_one_tailed < alpha and t_stat > 0:
    print("Conclusion: Since p < 0.05 and the t-statistic is positive, we reject the null hypothesis.")
    print("There is evidence that Q4 spending is significantly higher than Q1.")
else:
    print("Conclusion: We fail to reject the null hypothesis.")
    print("There is not enough evidence to conclude that Q4 spending is significantly higher than Q1.")

"""We tested to see if the total spending in Q4 (October–December) is significantly higher than in Q1 (January–March).

Null Hypothesis (H0): There is no difference in mean spending between Q4 and Q1  
Alternative Hypothesis (Ha): Spending is higher in Q4 than in Q1

- T-statistic: 1.51
- P-value: 0.0667

Conclusion: Since p > 0.05, we fail to reject the null hypothesis. There is not enough evidence that Q4 spending is significantly higher than Q1.

# Are Higher Quantities Associated With Lower Unit Prices?
"""

# Filter out outliers by keeping only the data below the 95th percentile of 'UnitPrice'
filtered_df = df[df['UnitPrice'] < df['UnitPrice'].quantile(0.95)]

# Calculate the Pearson correlation coefficient between 'Quantity' and 'UnitPrice'
corr = filtered_df['Quantity'].corr(filtered_df['UnitPrice'])

plt.figure(figsize=(10, 6))

sns.scatterplot(data=filtered_df, x='Quantity', y='UnitPrice', alpha=0.6)

sns.regplot(data=filtered_df, x='Quantity', y='UnitPrice', scatter=False, color='red')

# Display the correlation value as text on the plot
plt.text(1, filtered_df['UnitPrice'].max()*0.9, f'correlation: {corr:.2f}', fontsize=12, color='red')

plt.title('Relationship Between Quantity and Unit Price')
plt.xlabel('Quantity Purchased')
plt.ylabel('Unit Price')

# Adjust layout to prevent overlapping elements
plt.tight_layout()

plt.show()

filtered_df = df[df['UnitPrice'] < df['UnitPrice'].quantile(0.95)]
from scipy.stats import ttest_ind, pearsonr
# Run Pearson correlation test
r, p_value = pearsonr(filtered_df['Quantity'], filtered_df['UnitPrice'])

print(f"Correlation coefficient: {r:.2f}")
print(f"P-value: {p_value:.4f}")

"""#How does the distribution of unit prices vary across the top 4 most frequently purchased categories?


"""

# Group the DataFrame by 'Category' and sum the 'Quantity' for each category
# Then sort the categories in descending order of quantity and take the top 4
purshased_categories = df.groupby('Category')['Quantity'].sum().sort_values(ascending=False).head(4)

# Create a figure with specified size for better readability
plt.figure(figsize=(10, 6))

sns.barplot(x=purshased_categories.index, y=purshased_categories.values)

plt.title("Top Categories by Total Quantity Purchased")
plt.xlabel("Category")
plt.ylabel("Total Quantity")

# Rotate x-axis labels for better visibility (in case of long category names)
plt.xticks(rotation=45)

plt.tight_layout()

plt.show()

# Get the top 4 most frequently occurring categories (based on count, not quantity)
top_categories = df['Category'].value_counts().head(4).index

# Filter the DataFrame to include only rows that belong to the top 4 categories
top_category_data = df[df['Category'].isin(top_categories)]

plt.figure(figsize=(10, 6))

sns.boxplot(data=top_category_data, x='Category', y='UnitPrice')

plt.title("Distribution of Unit Prices in Top 4 Purchased Categories")
plt.xlabel("Category")
plt.ylabel("Unit Price")

plt.show()

top_categories = df['Category'].value_counts().head(4).index

# Filter data for those categories
top_category_data = df[df['Category'].isin(top_categories)]

# Plot with log scale for better visibility
plt.figure(figsize=(10, 6))
sns.boxplot(data=top_category_data, x='Category', y='UnitPrice')
plt.yscale('log')
plt.title("Distribution of Unit Prices in Top 4 Purchased Categories (Log Scale)")
plt.xlabel("Category")
plt.ylabel("Unit Price (Log Scale)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""#Which categories contribute the most to overall spending?

"""

# Group the data by 'Category' and sum the 'TotalCost' for each category
# Then sort the categories by total spending in descending order
category_spending = df.groupby('Category')['TotalCost'].sum().sort_values(ascending=False)

plt.figure(figsize=(10, 6))

sns.barplot(x=category_spending.values, y=category_spending.index)

plt.title('Total Spending by Category')
plt.xlabel('Total Spending')
plt.ylabel('Category')

plt.tight_layout()

plt.show()

"""#Which buyers are responsible for the most spending, and what do they purchase the most?"""

# Group the data by both 'Buyer' and 'Category', summing the 'TotalCost'
# Then reshape the result to have categories as columns (wide format)
buyer_category_spend = df.groupby(['Buyer', 'Category'])['TotalCost'].sum().unstack().fillna(0)

# Identify the top 5 buyers based on total spending across all categories
topfive_buyers = buyer_category_spend.sum(axis=1).sort_values(ascending=False).head(5).index

# Filter the data to include only the top 5 buyers
topfive_data = buyer_category_spend.loc[topfive_buyers]

topfive_data.plot(kind='bar', stacked=True, figsize=(10, 6), colormap='tab20')

plt.title('Top 5 Buyers: Spending Breakdown by Category')
plt.xlabel('Buyer')
plt.ylabel('Total Spending')

plt.legend(title='Category', bbox_to_anchor=(1.05, 1), loc='upper left')

plt.tight_layout()

plt.show()

"""# Is there a correlation between unit price and total cost across categories?"""

# Calculate the average unit price for each category
avg_unit_price = df.groupby('Category')['UnitPrice'].mean().reset_index()

# Calculate the total cost for each category
total_cost = df.groupby('Category')['TotalCost'].sum().reset_index()

# Merge the two DataFrames on the 'Category' column to combine average price and total cost
category_stats = pd.merge(avg_unit_price, total_cost, on='Category')

plt.figure(figsize=(8, 6))
sns.scatterplot(data=category_stats, x='UnitPrice', y='TotalCost', hue='Category')
plt.title('Unit Price vs Total Cost Across Categories')
plt.xscale('log')
plt.xlabel('Average Unit Price ')
plt.ylabel('Total Cost ')
plt.show()

"""# Extra Mile

**Time Series Breakdown**
"""

# Create a figure with specified size for better visibility
plt.figure(figsize=(10, 5))

sns.lineplot(data=df, x='PurchaseDate', y='TotalCost')

plt.title('Total Spending')
plt.xlabel('Date')
plt.ylabel('Total Cost')

plt.show()

"""#Total outliers spending

"""

# Calculate the 25th percentile (Q1) of 'UnitPrice'
Q1 = df['UnitPrice'].quantile(0.25)

# Calculate the 75th percentile (Q3) of 'UnitPrice'
Q3 = df['UnitPrice'].quantile(0.75)

# Compute the interquartile range (IQR)
IQR = Q3 - Q1

# Calculate the lower bound for outliers
lower_bound = Q1 - 1.5 * IQR

# Calculate the upper bound for outliers
upper_bound = Q3 + 1.5 * IQR

# Identify rows where 'UnitPrice' is outside the IQR bounds (outliers)
iqr_outliers = df[(df['UnitPrice'] < lower_bound) | (df['UnitPrice'] > upper_bound)]

# Sum the 'TotalCost' of these outlier transactions to see their overall spending impact
total_iqr_outlier_spending = iqr_outliers['TotalCost'].sum()

print("Outlier Transactions (IQR method):")
print(iqr_outliers[['TransactionID', 'Category', 'UnitPrice', 'TotalCost']].head())

print(total_iqr_outlier_spending)

"""# Timeline after deleting the outliers"""

# Filter the DataFrame to exclude outliers based on UnitPrice using the previously calculated bounds
df_no_outliers = df[(df['UnitPrice'] >= lower_bound) & (df['UnitPrice'] <= upper_bound)]

plt.figure(figsize=(10, 5))

sns.lineplot(data=df_no_outliers, x='PurchaseDate', y='TotalCost')

plt.title('Total Spending Over Time (Without Unit Price Outliers)')
plt.xlabel('Date')
plt.ylabel('Total Cost')

plt.show()

"""#Buyer Spending Profiles"""

buyer_profiles = df.groupby('Buyer').agg(
    TotalSpend=('TotalCost', 'sum'),
    NumPurchases=('TransactionID', 'count'),
    AvgQuantity=('Quantity', 'mean')
).reset_index()

top_buyers = buyer_profiles.sort_values(by='TotalSpend', ascending=False)

plt.figure(figsize=(12, 6))
sns.barplot(data=top_buyers.head(10), x='TotalSpend', y='Buyer')
plt.title('Top 10 Buyers by Total Spend')
plt.xlabel('Total Spend ')
plt.ylabel('Buyer')
plt.tight_layout()
plt.show()

# Display the top 10 buyers' statistics
top_buyers.head(10)

"""# Do Top Buyers Spend More Per Purchase?"""

top_buyer_names = top_buyers.head(10)['Buyer']
top5_buyers = top_buyer_names.head(5)
df_top5 = df[df['Buyer'].isin(top5_buyers)]
plt.figure(figsize=(10, 6))
sns.boxplot(data=df_top5, x='Buyer', y='Quantity')
plt.title('Quantity per Transaction for Top 5 Buyers')
plt.xlabel('Buyer')
plt.ylabel('Quantity')
plt.grid(True)
plt.tight_layout()
plt.show()

"""Null Hypothesis (H₀): All top 5 buyers have the same average quantity per transaction.

Alternative Hypothesis (H₁): At least one buyer has a significantly different average quantity.
"""

from scipy.stats import f_oneway
groups = [df[df['Buyer'] == buyer]['Quantity'] for buyer in top5_buyers]
f_stat, p_value = f_oneway(*groups)
print(f"ANOVA F-statistic: {f_stat:.4f}")
print(f"P-value: {p_value:.4f}")

if p_value < 0.05:
    print("Result: Significant difference in quantity between at least two buyers.")
else:
    print("Result: No significant difference in quantity between buyers.")

"""#Does Category, Month, or their interaction significantly affect TotalCost?"""

df['PurchaseDate'] = pd.to_datetime(df['PurchaseDate'])

# Extract month name
df['Month'] = df['PurchaseDate'].dt.strftime('%B')  # e.g., January, February

month_order = ['January', 'February', 'March', 'April', 'May', 'June',
             'July', 'August', 'September', 'October', 'November', 'December']
df['Month'] = pd.Categorical(df['Month'], categories=month_order, ordered=True)

pivot_table = df.pivot_table(index='Category', columns='Month', values='TotalCost', aggfunc='sum', fill_value=0)

# Plot the heatmap
plt.figure(figsize=(14, 6))
sns.heatmap(pivot_table, annot=True, fmt=".0f", cmap="YlGnBu", cbar_kws={'label': 'Total Spend '})
plt.title('Total Spending by Category and Month')
plt.xlabel('Month')
plt.ylabel('Category')
plt.tight_layout()
plt.show()

from scipy.stats import f_oneway

# Group total cost by month
month_groups = [group['TotalCost'] for name, group in df.groupby('Month')]
f_stat, p_val = f_oneway(*month_groups)

print(f"F-statistic: {f_stat:.4f}")
print(f"P-value: {p_val:.4f}")

if p_val < 0.05:
    print(" Significant difference in spending across months.")
else:
    print(" No significant difference in spending across months.")

# Group total cost by category
category_groups = [group['TotalCost'] for name, group in df.groupby('Category')]
f_stat, p_val = f_oneway(*category_groups)
print(f"F-statistic: {f_stat:.4f}")
print(f"P-value: {p_val:.4f}")

if p_val < 0.05:
    print(" Significant difference in spending across category.")
else:
    print(" No significant difference in spending across category.")

"""#Is there any correlation between categories and spending?

"""

pivot_table = df.pivot_table(index='Category', columns='Month', values='TotalCost', aggfunc='sum', fill_value=0)

category_corr = pivot_table.T.corr()
plt.figure(figsize=(10, 6))
sns.heatmap(category_corr, annot=True, cmap='coolwarm', center=0)
plt.title('Correlation of Spending Patterns Between Categories')
plt.show()